name: On-demand Build

on:
  repository_dispatch:
    types: [run-build]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/lynfera/build-runner:latest

    steps:
      - name: Run commands in container
        run: |
          echo "Container is running....."
