name: On-demand Build
run-name: Build ${{ github.event.client_payload.projectId }} â€“ ${{ github.event.client_payload.deploymentId }}
on:
  repository_dispatch:
    types: [run-build]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amal664/lynfera-builds
    env:
      DEPLOYMENT_ID: ${{ github.event.client_payload.deploymentId }}
      PROJECT_ID: ${{ github.event.client_payload.projectId }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      CLOUD_BUCKET: ${{ secrets.CLOUD_BUCKET }}
      CLOUD_ENDPOINT: ${{ secrets.CLOUD_ENDPOINT }}
      CLOUD_SECRETKEY: ${{ secrets.CLOUD_SECRETKEY }}
      CLOUD_ACCESSKEY: ${{ secrets.CLOUD_ACCESSKEY }}
      CONTAINER_API_TOKEN: ${{ secrets.CONTAINER_API_TOKEN }}
      STORAGE_SERVER_ENDPOINT: ${{ secrets.STORAGE_SERVER_ENDPOINT }}
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
    steps:
      - name: Run commands in container
        run: |
          echo "Container is running....."
      - name: Run commands in container
        run: |
          echo "::notice::Building project $PROJECT_ID"
      - name: Run build entrypoint
        run: |
          /home/app/main.sh

          
  error_handle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install kafkajs@2.2.4

      - name: Report starting error
        env:
          KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
        run: node scripts/produce.js
